### ISSUE TITLE
Suitable for Windows?

### ISSUE THREAD

**Issue by bcnx** [YSmetana/raid_arcconf_zabbix_lld#7]
Hi,

is this template supposed to work on Windows? The description on https://www.zabbix.com/ru/integrations/adaptec says it does but the Readme suggests Linux.

Thanks!

BC

**Comment by YuriySm** [comment]
Hello. No, sorry. Because of hardcoded Linux commands, it is not suitable for Windows. 

But you can modify it though to have the same output.

**Comment by bcnx** [comment]
> Hello. No, sorry. Because of hardcoded Linux commands, it is not suitable for Windows.
> 
> But you can modify it though to have the same output.

Hi YSmetana, I suppose you mean changing the Userparameter so it uses arcconf in Windows?

Thanks,

BC

**Comment by bcnx** [comment]
I decided to have a go at a Windows implementation and while testing the Python file I get:

C:\install\zabbix>.\raid_arcconf_zabbix_lld.py` --verbose pd -1 lld
Traceback (most recent call last):
  File "C:\install\zabbix\raid_arcconf_zabbix_lld.py", line 204, in <module>
    res = run(command)
  File "C:\install\zabbix\raid_arcconf_zabbix_lld.py", line 77, in run
    res = check_output(commands, stderr=open(os.devnull, 'wb'))
  File "C:\Python27\lib\subprocess.py", line 530, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Any idea what causes this?

Cheers,

BC

**Comment by YuriySm** [comment]
Sorry for not replying to you in time. I do not use it anymore.
